//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSalesApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniSalesApp.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة لا يمكن ان تكون سالبة.
        /// </summary>
        internal static string AmountCantBeNegative {
            get {
                return ResourceManager.GetString("AmountCantBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد مطلوب.
        /// </summary>
        internal static string BalanceIsRequired {
            get {
                return ResourceManager.GetString("BalanceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنك به حركات.
        /// </summary>
        internal static string BankHasTransaction {
            get {
                return ResourceManager.GetString("BankHasTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنك غير موجود.
        /// </summary>
        internal static string BankNotFound {
            get {
                return ResourceManager.GetString("BankNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاتورة غير موجودة.
        /// </summary>
        internal static string BillNotFound {
            get {
                return ResourceManager.GetString("BillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن اضافة او تعديل الحركات في اخر يومية فقط.
        /// </summary>
        internal static string CanCreateOrEditTransactionOnlyInLastDaily {
            get {
                return ResourceManager.GetString("CanCreateOrEditTransactionOnlyInLastDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن فقط حذف او تعديل اخر يومية.
        /// </summary>
        internal static string CanOnlyDeleteOrUpdateLastDaily {
            get {
                return ResourceManager.GetString("CanOnlyDeleteOrUpdateLastDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود مطلوب.
        /// </summary>
        internal static string CodeIsRequired {
            get {
                return ResourceManager.GetString("CodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل غير موجود.
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ اليومية يجب ان يكون اكير من تاريخ اخر يومية.
        /// </summary>
        internal static string DateMustBeGreaterThanLastDailyDate {
            get {
                return ResourceManager.GetString("DateMustBeGreaterThanLastDailyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الحذف.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        internal static string DeleteSuccessfuly {
            get {
                return ResourceManager.GetString("DeleteSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم لا يمكن ان تكون صفر او سالب.
        /// </summary>
        internal static string DiscountCanNotBeNegative {
            get {
                return ResourceManager.GetString("DiscountCanNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم لا يمكن ان يكون سالب.
        /// </summary>
        internal static string DiscountCantBeNegative {
            get {
                return ResourceManager.GetString("DiscountCantBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيد النهاية لا يمكن ان يكون سالب.
        /// </summary>
        internal static string EndAmountCantBeNegative {
            get {
                return ResourceManager.GetString("EndAmountCantBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الصنف.
        /// </summary>
        internal static string EnterMaterial {
            get {
                return ResourceManager.GetString("EnterMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الاصناف.
        /// </summary>
        internal static string EnterMaterials {
            get {
                return ResourceManager.GetString("EnterMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل السعر.
        /// </summary>
        internal static string EnterPrice {
            get {
                return ResourceManager.GetString("EnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الكمية.
        /// </summary>
        internal static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ غير صحيح.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاتورة غير موجودة.
        /// </summary>
        internal static string InvoiceNotFound {
            get {
                return ResourceManager.GetString("InvoiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصنف موجود بالفعل.
        /// </summary>
        internal static string MaterialIsAlreadyExist {
            get {
                return ResourceManager.GetString("MaterialIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصنف غير موجود.
        /// </summary>
        internal static string MaterialNotFound {
            get {
                return ResourceManager.GetString("MaterialNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم مطلوب.
        /// </summary>
        internal static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التليفون مطلوب.
        /// </summary>
        internal static string PhoneIsRequired {
            get {
                return ResourceManager.GetString("PhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الشراء مطلوب.
        /// </summary>
        internal static string PurchasePriceIsRequired {
            get {
                return ResourceManager.GetString("PurchasePriceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكميه لا يمكن ان تكون صفر او سالبه.
        /// </summary>
        internal static string QuantityCanNotBeNegative {
            get {
                return ResourceManager.GetString("QuantityCanNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        internal static string SaveSuccessfuly {
            get {
                return ResourceManager.GetString("SaveSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر مورد.
        /// </summary>
        internal static string SelectSupplier {
            get {
                return ResourceManager.GetString("SelectSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر عميل.
        /// </summary>
        internal static string SellectCustomer {
            get {
                return ResourceManager.GetString("SellectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر لا يمكن ان يكون صفر او سالب.
        /// </summary>
        internal static string SellPriceCanNotBeNegative {
            get {
                return ResourceManager.GetString("SellPriceCanNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر البيع مطلوب.
        /// </summary>
        internal static string SellPriceIsRequired {
            get {
                return ResourceManager.GetString("SellPriceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسلسل مطلوب.
        /// </summary>
        internal static string SerialIsRequired {
            get {
                return ResourceManager.GetString("SerialIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيد البداية لايمكن ان يكون سالب.
        /// </summary>
        internal static string StartAmountCantBeNegative {
            get {
                return ResourceManager.GetString("StartAmountCantBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليومية غير موجودة.
        /// </summary>
        internal static string StoreDailyNotFound {
            get {
                return ResourceManager.GetString("StoreDailyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المورد غير موجود.
        /// </summary>
        internal static string SupplierNotFound {
            get {
                return ResourceManager.GetString("SupplierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوميه بها حركات.
        /// </summary>
        internal static string TheDailyHasTransaction {
            get {
                return ResourceManager.GetString("TheDailyHasTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الحركه لا يمكن ان يكون اقل من تاريخ البداية.
        /// </summary>
        internal static string TransactionDateCantBeLessThanStartDate {
            get {
                return ResourceManager.GetString("TransactionDateCantBeLessThanStartDate", resourceCulture);
            }
        }
    }
}
